name: gluco
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  dash_chat_2: ^0.0.20
  fl_chart: ^0.68.0
  intl: ^0.19.0
  flutter_localization: ^0.2.0
  iconsax_flutter: ^1.0.0
  image_picker: ^1.1.2
  easy_date_timeline: ^1.1.3
  pretty_dio_logger: ^1.3.1
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  jwt_decoder: ^2.0.1
  uuid: ^4.4.0
  firebase_messaging: ^15.0.1
  google_generative_ai: ^0.4.3
  # flutter_datetime_picker: ^1.5.1
  # firebase_auth: ^5.11.1
  # cloud_firestore: ^4.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dio: ^5.4.3+1
  bloc: ^8.1.4
  smooth_page_indicator: ^1.1.0
  adaptive_theme: ^3.6.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  pedometer: ^4.0.1
  http_mock_adapter: ^0.6.1
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 