name: gluco
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  dash_chat_2: ^0.0.20
  fl_chart: ^0.68.0
  flutter_localization: ^0.2.0
  iconsax_flutter: ^1.0.0
  image_picker: ^1.1.2
  easy_date_timeline: ^1.1.2
  intl: ^0.17.0
  camera: ^0.11.0+1
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  jwt_decoder: ^2.0.1
  uuid: ^4.4.0
  firebase_messaging: ^15.0.1
  percent_indicator: ^4.0.1
  wakelock: ^0.6.1
  google_generative_ai: ^0.4.3
  gap: ^3.0.1
  provider: ^6.1.2
  firebase_storage: ^12.1.1
  image_stack: ^2.1.1
  flutter_svg: ^2.0.10+1
dependency_overrides:
  intl: ^0.17.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dio: ^5.4.3+1
  smooth_page_indicator: ^1.1.0
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/

 
 